@bearerToken = Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiZW1haWwiOiJqY3NjZW5lMzY3QGdtYWlsLmNvbSIsIm5pY2tuYW1lIjoi7KG47JqpIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImV4cCI6MTc1MTgwODYxNywiaWF0IjoxNzUxODA1MDE3fQ.fFUPs9y35ZUq1BlqDSiZWwg8BzZivGykoGLUp03oFLk

### 테스트 로그인
POST http://localhost:8080/users/test-login?userId=2

### 장소 좋아요
< {%
    request.variables.set("placeId", [350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360])
%}
POST http://localhost:8080/places/{{placeId}}/like
Authorization: {{bearerToken}}

### Json data 저장
POST http://localhost:8080/places/write-json
Authorization: {{bearerToken}}